services:
  db:
    image: postgres:16.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: backend-agencia
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
